package com.festival.everyday.core.notice.domain;

public enum NoticeType {
    LABOR_RECRUIT_DEAD, COMPANY_RECRUIT_DEAD, COMPANY_APPLIED, LABOR_APPLIED, APPLY_ACCEPTED, APPLY_DENIED, LABOR_DUE, COMPANY_DUE, FESTIVAL_INTEREST
}
